/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container': '#201f1f',
        'on-tertiary-fixed-variant': '#004e5d',
        'tertiary-container': '#319db6',
        'surface-tint': '#ffb3b3',
        'on-primary-fixed': '#400009',
        'error-container': '#93000a',
        'surface-container-lowest': '#0e0e0e',
        'surface-dim': '#131313',
        'on-surface-variant': '#e4beb9',
        'on-error-container': '#ffdad6',
        primary: '#ffb3b3',
        'primary-fixed-dim': '#ffb3b3',
        background: '#131313',
        secondary: '#c8c6c5',
        'on-tertiary-container': '#002e39',
        'surface-container-high': '#2a2a2a',
        'tertiary-fixed': '#afecff',
        'primary-fixed': '#ffdad9',
        'inverse-on-surface': '#313030',
        'on-surface': '#e5e2e1',
        error: '#ffb4ab',
        'inverse-surface': '#e5e2e1',
        outline: '#ab8985',
        'on-primary-container': '#5b0011',
        'on-primary-fixed-variant': '#920021',
        'surface-container-low': '#1c1b1b',
        'on-secondary-fixed': '#1b1c1c',
        'surface-bright': '#3a3939',
        'on-secondary': '#303030',
        'on-background': '#e5e2e1',
        'surface-container-highest': '#353534',
        'inverse-primary': '#bf002e',
        tertiary: '#72d4ef',
        'on-tertiary-fixed': '#001f27',
        'secondary-fixed-dim': '#c8c6c5',
        'surface-variant': '#353534',
        'tertiary-fixed-dim': '#72d4ef',
        'secondary-fixed': '#e5e2e1',
        'secondary-container': '#474746',
        'on-error': '#690005',
        'on-secondary-container': '#b7b5b4',
        'on-primary': '#680014',
        'on-secondary-fixed-variant': '#474746',
        'outline-variant': '#5b403d',
        surface: '#131313',
        'primary-container': '#ff525f',
        'on-tertiary': '#003641',
      },
      fontFamily: {
        headline: ['Space Grotesk'],
        body: ['Inter'],
        label: ['Inter'],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
